### ISSUE TITLE
Change Absolute Paths to Relative Paths

### ISSUE THREAD

**Issue by ChlorinePentoxide** [reshmaharidhas/FibonacciGenerator#1]
## Location
File Name: FibonacciGenerator.java
Line: 35

## Problem:
Contains a absolute path for the window icon in the developers directory instead of a relative
path which would have made the code reproducible across different environments.

## Probable Solution(s):
* Upload the requisite image and change the absolute path to a relative path.
* (or) Remove the need for an window icon

**Comment by reshmaharidhas** [comment]
Resolved icon location by changing to relative path

**Comment by ChlorinePentoxide** [comment]
Thanks! There is a pull request as well which takes of the other issue.
